// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhqS5Jm-9M_mxd9sizUaWzKBWa2jUqto',
    appId: '1:91651391747:web:a9c535d34a63d5628a2936',
    messagingSenderId: '91651391747',
    projectId: 'the-grimoire-95acd',
    authDomain: 'the-grimoire-95acd.firebaseapp.com',
    storageBucket: 'the-grimoire-95acd.firebasestorage.app',
    measurementId: 'G-BWRBGTTLXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf95Rbq7paarKP0HmDr_nKxe6be03VQSg',
    appId: '1:91651391747:android:82e2ccca734a8ff18a2936',
    messagingSenderId: '91651391747',
    projectId: 'the-grimoire-95acd',
    storageBucket: 'the-grimoire-95acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8YTHDdZCsaEsMypV9MDGt8Mo38Brk3r8',
    appId: '1:91651391747:ios:b07eb6494cd0d0cb8a2936',
    messagingSenderId: '91651391747',
    projectId: 'the-grimoire-95acd',
    storageBucket: 'the-grimoire-95acd.firebasestorage.app',
    iosBundleId: 'com.example.theGrimoire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8YTHDdZCsaEsMypV9MDGt8Mo38Brk3r8',
    appId: '1:91651391747:ios:b07eb6494cd0d0cb8a2936',
    messagingSenderId: '91651391747',
    projectId: 'the-grimoire-95acd',
    storageBucket: 'the-grimoire-95acd.firebasestorage.app',
    iosBundleId: 'com.example.theGrimoire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUhqS5Jm-9M_mxd9sizUaWzKBWa2jUqto',
    appId: '1:91651391747:web:3e9ea8befb5323ed8a2936',
    messagingSenderId: '91651391747',
    projectId: 'the-grimoire-95acd',
    authDomain: 'the-grimoire-95acd.firebaseapp.com',
    storageBucket: 'the-grimoire-95acd.firebasestorage.app',
    measurementId: 'G-GXQWHZNCZQ',
  );
}
